version: "3.3"

services:
  db:
    image: postgres:15
    container_name: movie-api-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: moviedb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - architecture-network-app

  seq-input-gelf:
    image: datalust/seq-input-gelf:latest
    depends_on:
      - seq
    ports:
      - "12201:12201/udp"
    environment:
      SEQ_ADDRESS: "http://seq:5341"
    restart: unless-stopped

  seq:
    image: datalust/seq:latest
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORD=admin
    ports:
      - "5341:80"
    volumes:
      - seqdata:/data
    networks:
      - architecture-network-app
    restart: unless-stopped

  mymovieapp.api:
    image: ghcr.io/renan-marcel-org/my-movie-app-api:latest
    environment:
      ConnectionString:Database: "Host=db:5432; Database=moviedb-app2; Username=postgres; Password=postgres"
      ASPNETCORE_HTTP_PORTS: "8080"
      OMDb:ApiKey: "9c9d85ad"
      OMDb:ApiUri: "http://www.omdbapi.com"
      Seq:ServerUrl: "http://seq:80"
      Seq:ApiKey: ""
    ports:
      - "58114:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - architecture-network-app
    depends_on:
      - db
      - seq

volumes:
  pgdata:
  seqdata:

networks:
  architecture-network-app:
    driver: bridge
    name: architecture-network-app